# Generated by Django 5.2.4 on 2025-07-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='likedpost',
            name='user',
        ),
        migrations.AddField(
            model_name='likedpost',
            name='user_id',
            field=models.CharField(default='john', max_length=255),
        ),
        migrations.AlterField(
            model_name='likedpost',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
