# Generated by Django 5.2.4 on 2025-07-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_likedpost_options_remove_likedpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
