# Generated by Django 5.2.4 on 2025-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='image_link',
            field=models.URLField(default='https://th.bing.com/th?id=OPAC.AdlaqX2S9AaY%2bw474C474&w=592&h=550&o=5&dpr=1.3&pid=21.1', max_length=1000),
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='sub_category',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='brandproduct',
            name='category',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
